### ISSUE TITLE
OECD Lithuania

### ISSUE THREAD

**Issue by joshbrinks** [cjyetman/memberstates#3]
Nice package, very convenient at times.

Lithuania is now an OECD member if you care to add it.

**Comment by cjyetman** [comment]
Thanks, and sorry for the long delay in my response. Happily surprised to hear that someone is using this. I ran the scraper and updated all the lists in 4397e5cc0cadfb38c5f40100d7bf1b099994dd90. Not exactly sure what all has changed, but I checked that Lithuania is now included in `memberstates$oecd`
```r
"Lithuania" %in% memberstates$oecd$country.name
# [1] TRUE
```
